### ISSUE TITLE
Separate resource quotas for admin deployment and cronjob

### ISSUE THREAD

**Issue by cberge908** [cloudquery/helm-charts#261]
### Describe the resource.

Currently the helm chart has only one option to set resource limits/ requests. This is then applied to both resources, admin deployment and cronjob. I would be nice if this can be changed to something like this:

```yaml
resources:
    admin:
      requests:
        memory: 24Gi
        cpu: 10
    cronjob:
      limits:
        memory: 62Gi
        cpu: 12
```

### Use Case

We want to run the cronjob on a separate node which is dedicated for QC only. Assuming that the admin deployment does not need the same amount of resources as the cronjob we would like to have the option to scale them individually. Otherwise, it would be also an option to fix the resource quotas of the admin deployment and change the chart to only affect the resources of the cronjob.
