### ISSUE TITLE
[Bug] secretRef

### ISSUE THREAD

**Issue by Hokwang** [cloudquery/helm-charts#278]
### Describe the bug

Hi,

recently committed PR has problem,
in my custom values.yaml is below, and very basic and simple.
And it works previous version of helm chart.
now, I can't upgrade.

```
serviceAccount:
  enabled: true

envRenderSecret:
  CQ_DSN: "postgresql://postgres:pw@postgresql.cloudquery:5432/cloudquery?sslmode=disable"


schedule: "0 0 * * *"

config: |
  kind: source
  spec:
    name: aws
    path: cloudquery/aws
    version: "v15.2.0"
    tables:
    ...
    destinations: ["postgresql"]
    spec:
      regions:
        - us-east-1
      accounts:
      ...
  ---
  kind: destination
  spec:
    name: postgresql
    path: cloudquery/postgresql
    version: "v2.1.4"
    spec:
      connection_string: ${CQ_DSN}
```

### Expected Behavior

update success.

### Steps to Reproduce

after `helm repo update`,
```
$ helm -n cloudquery upgrade cloudquery cloudquery/cloudquery -f cloudquery-values.yaml
Error: UPGRADE FAILED: template: cloudquery/templates/secret.yaml:11:16: executing "cloudquery/templates/secret.yaml" at <.Values.tplConfig>: can't evaluate field Values in type interface {}
```

### Possible Solution

I think that you need to change templates/secret.yaml file 1st line.
`{{- if not .Values.secretRef }}` to `{{- if .Values.secretRef }}`

### Provider and CloudQuery version

chart version : 14.1.3 app version : 2.4
